import { AutoresponderOrder } from '@/services/api/autoresponderOrders.api'

export const mockAutoresponderOrders: AutoresponderOrder[] = [
  {
    id: '1',
    orderDate: '30/01/2026',
    orderNumber: '701-4038788-1857837',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '2',
    orderDate: '30/01/2026',
    orderNumber: '701-9634352-1806631',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '3',
    orderDate: '30/01/2026',
    orderNumber: '111-5732888-0153061',
    marketplace: 'Amazon.com',
    productSku: 'B0FCZV4BDT',
    productTitle: 'BEDDORA-MFSS-4PC-QUEEN-TITANIUM\nBeddora Queen Sheets Set – 4 Piece Soft & Cooling Queen Bed Sheets Set – Deep Poc... ets (Gray)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '4',
    orderDate: '30/01/2026',
    orderNumber: '111-4079436-3957031',
    marketplace: 'Amazon.com',
    productSku: 'B0FD113D3K',
    productTitle: 'BEDDORA-MFSS-4PC-QUEEN-INSIGNIA-BLUE\nBeddora Queen Sheets Set – 4 Piece Soft & Cooling Queen Bed Sheets Set – Deep Pock...ets (Blue)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '5',
    orderDate: '30/01/2026',
    orderNumber: '702-2529841-3183405',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '6',
    orderDate: '30/01/2026',
    orderNumber: '702-6131060-1456250',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '7',
    orderDate: '30/01/2026',
    orderNumber: '701-3949320-3617024',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '8',
    orderDate: '30/01/2026',
    orderNumber: '701-8931437-3132248',
    marketplace: 'Amazon.ca',
    productSku: 'B0FNBXLBWJ',
    productTitle: 'EDDORA-PP-KINGQ2PK-WHT-NEW1\nBeddora 2 Pack Pillow Protectors King Size – Waterproof Zippered Pillow Case Covers.... r Sleeping',
    productImage: 'https://via.placeholder.com/50x50?text=Pillow',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '9',
    orderDate: '30/01/2026',
    orderNumber: '701-1352862-7907401',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '10',
    orderDate: '30/01/2026',
    orderNumber: '702-5526856-8069027',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '11',
    orderDate: '30/01/2026',
    orderNumber: '111-2687704-9671414',
    marketplace: 'Amazon.com',
    productSku: 'B0FCZV4BDT',
    productTitle: 'BEDDORA-MFSS-4PC-QUEEN-TITANIUM\nBeddora Queen Sheets Set – 4 Piece Soft & Cooling Queen Bed Sheets Set – Deep Poc... ets (Gray)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '12',
    orderDate: '30/01/2026',
    orderNumber: '701-7063304-6426623',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RQZZ8P',
    productTitle: 'BT-Light Blue\nBeddora Luxury Bath Towels – 100% Cotton, Extra Soft Oversized 27x54 Large Sky Blu...h – 1 Pack',
    productImage: 'https://via.placeholder.com/50x50?text=Towel',
    status: 'pending_data',
    blackListed: false,
  },
  {
    id: '13',
    orderDate: '30/01/2026',
    shippingDate: '30/01/2026',
    orderNumber: '701-5633288-0777834',
    marketplace: 'Amazon.ca',
    productSku: 'B0F4RTTQXQ',
    productTitle: 'Hangers-50Pack\nBeddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for Closet - Felt Hang... esses,Suit',
    productImage: 'https://via.placeholder.com/50x50?text=Hangers',
    status: 'pending_data',
    blackListed: false,
  },
]
