import { AutoresponderProduct } from '@/services/api/autoresponderProducts.api'

export const mockAutoresponderProducts: AutoresponderProduct[] = [
  {
    id: '1',
    sku: 'B0DGG3T1DL',
    title: 'BEDDORA-Queen Bed Sheets Set - 4 Piece Bed Sheets Queen Size Set - Ultra-Soft Deep Pocket Queen Sheet Set, Wrinkle-Free Microfiber Sheet Set Queen Size, Easy Care Hotel Luxury Queen Size Bed...',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '2',
    sku: 'B0DG6RFF77',
    title: 'Beddora Queen Size Comforter - All Season White Quilted Duvet Insert 200GSM - Ultra Soft Light Weight Alternative Box Stitched Bed Comforter with Corner Tabs - Machine Washable',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '3',
    sku: 'B0DG6HG7S8',
    title: 'Beddora Waterproof Mattress Protector Queen Size, Breathable Quilted Mattress Cover – Bed Bug Proof Mattress Pad, Soft & Noiseless Fitted Sheet Stretches up to 16 inches Deep (White)',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '4',
    sku: 'B0DZPSML6B',
    title: 'Beddora Bamboo King Mattress Protector – 100% Waterproof Mattress Cover Lit Bed Cover, Ultra Soft Breathable Viscose from Bamboo Pad, Fitted Style with Stretchable Deep Pockets up to Size 18-21"',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '5',
    sku: 'B0DZP6DDMQ',
    title: 'Beddora Bamboo Queen Mattress Protector – 100% Waterproof Mattress Cover Lit Bed Cover, Ultra Soft Breathable Viscose from Bamboo Pad, Fitted Style with Stretchable Deep Pockets up to Size 18-...',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '6',
    sku: 'B0F1BC8C91',
    title: 'Beddora Queen Sheets Set – 4 Piece Soft & Cooling Queen Bed Sheets Set – Deep Pockets, Wrinkle-Resistant, Breathable Microfiber– Includes Fitted, Flat Sheet & Pillowcase Sets (Black)',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '7',
    sku: 'B0F1BG6QPK',
    title: 'Beddora Double Sheets Set – 4 Piece Soft & Cooling Double Bed Sheets Set – Deep Pockets, Wrinkle-Resistant, Breathable Microfiber– Includes Fitted, Flat Sheet & Pillowcase Sets (Gray)',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '8',
    sku: 'B0F1BPB8DG',
    title: 'Beddora King Sheets Set – 4 Piece Soft & Cooling King Bed Sheets Set – Deep Pockets, Wrinkle-Resistant, Breathable Microfiber– Includes Fitted, Flat Sheet & Pillowcase Sets (White)',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '9',
    sku: 'B0F1C9V637',
    title: 'Beddora Bed Sheets Set – 4-Piece Cooling Deep Pocket Sheet Set – Ultra-Soft, Wrinkle-Free Microfiber Sheet Set, Hotel Luxury Easy-Care Bedsheets Set (Harbor Gray) (Blue, Double)',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '10',
    sku: 'B0F4DQPST5',
    title: 'Beddora 3-Piece Brown Duvet Insert Queen Size, All Season Comforter Set King Size Cotton Soft Quilted Down Alternative Box Stitched Bed Comforter with Button Closure & Corner Ties+2 Pillow Shams',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '11',
    sku: 'B0F4DRLCSP',
    title: 'Beddora 3-Piece Brown Duvet Insert Queen Size, All Season Comforter Set Queen Size Cotton Soft Quilted Down Alternative Box Stitched Bed Comforter with Button Closure & Corner Ties+2 Pillow...',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
  {
    id: '12',
    sku: 'B0F4DSNP74',
    title: 'Beddora 3-Piece White Duvet Insert Queen Size, All Season Comforter Set Queen Size Cotton Soft Quilted Down Alternative Box Stitched Bed Comforter with Button Closure & Corner Ties+2 Pillow...',
    imageUrl: 'https://via.placeholder.com/60x60?text=Product',
    campaign: '',
    nickname: '',
  },
]
