import { Alert, AlertSummary } from '@/services/api/alerts.api'

export const mockAlertSummary: AlertSummary = {
  major: {
    unresolved: 267,
    resolved: 0,
  },
  minor: {
    unresolved: 110,
    resolved: 0,
  },
  total: {
    unresolved: 377,
    resolved: 0,
  },
}

export const mockAlerts: Alert[] = [
  {
    id: '1',
    date: '30/01/2026',
    description: 'Time to reorder: Soon',
    productSku: 'B0F1BC8C91',
    productTitle: 'SKU Beddora-MF-4PC-SHEET SET-CAVIAR-QUEEN\nBeddora Queen Sheets Set – 4 Piece Soft & Cooling Queen ... ts (Black)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    comment: '',
    marketplace: 'Amazon.com',
    marketplaceCode: 'US',
    priority: 'major',
    resolved: false,
    type: 'reorder',
  },
  {
    id: '2',
    date: '30/01/2026',
    description: 'Time to reorder: Yes',
    productSku: 'X0D4UQVSHZ',
    productTitle: 'SKU BDMTFHROWPILLOW4PK18X18WHITE\nBeddora 18x18 Pillow Inserts, Set of 4, White, Indoor Deco...on Inserts',
    productImage: 'https://via.placeholder.com/50x50?text=Pillow',
    comment: '',
    marketplace: 'Amazon.ca',
    marketplaceCode: 'CA',
    priority: 'major',
    resolved: false,
    type: 'reorder',
  },
  {
    id: '3',
    date: '30/01/2026',
    description: 'Time to reorder: Yes',
    productSku: 'B0F5X1ZGJI',
    productTitle: '2 products\nBeddora 4 Piece King Size Bed Sheets Set - Ultra-Soft Deep... King Size',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    comment: '',
    marketplace: 'Amazon.ca',
    marketplaceCode: 'CA',
    priority: 'major',
    resolved: false,
    type: 'reorder',
  },
  {
    id: '4',
    date: '30/01/2026',
    description: 'Running out of stock: Soon\nTime to reorder: Yes',
    productSku: 'B0DZPX6DMQ',
    productTitle: 'SKU BambooMP-Queen\nBeddora Bamboo Queen Mattress Protector – 100% Wate... ize 18-21"',
    productImage: 'https://via.placeholder.com/50x50?text=Mattress',
    comment: '',
    marketplace: 'Amazon.ca',
    marketplaceCode: 'CA',
    priority: 'major',
    resolved: false,
    type: 'out_of_stock',
  },
  {
    id: '5',
    date: '30/01/2026',
    description: 'Time to reorder: Soon',
    productSku: 'B0FCZTQL1N',
    productTitle: 'SKU BEDDORA-MFSS-4PC-KING-TURTLEDOVE\nBeddora King Sheets Set – 4 Piece Soft & Cooling King Bed ... ts (Beige)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    comment: '',
    marketplace: 'Amazon.com',
    marketplaceCode: 'US',
    priority: 'major',
    resolved: false,
    type: 'reorder',
  },
  {
    id: '6',
    date: '29/01/2026',
    description: 'Time to reorder: Yes',
    productSku: 'B0DZPX6DMQ',
    productTitle: 'SKU BambooMP-Queen\nBeddora Bamboo Queen Mattress Protector – 100% Wate... ize 18-21"',
    productImage: 'https://via.placeholder.com/50x50?text=Mattress',
    comment: '',
    marketplace: 'Amazon.ca',
    marketplaceCode: 'CA',
    priority: 'major',
    resolved: false,
    type: 'reorder',
  },
  {
    id: '7',
    date: '29/01/2026',
    description: 'Image changed from',
    productSku: 'B0FCZT13SN',
    productTitle: 'SKU BEDDORA-MFSS-4PC-KING-CAVIAR\nBeddora King Sheets Set – 4 Piece Soft & Cooling King Bed ... ts (Black)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    comment: '',
    marketplace: 'Amazon.com',
    marketplaceCode: 'US',
    priority: 'major',
    resolved: false,
    type: 'image_change',
  },
  {
    id: '8',
    date: '29/01/2026',
    description: 'Title changed from "Beddora King Sheet Set – 4 Piece Soft & Cooling Bed Red Sheets Set – Deep Pockets, Wrinkle-Free, Microfiber Luxury Bed Sheets - Breathable Microfiber Bedding for Women, Men & Kids – Includes Fitted, Flat Sheet & 2 Pillowcases (Black)" to "Beddora King Sheets Set – 4 Piece Soft & Cooling King Bed Sheets Set – Deep Pockets, Wrinkle-Resistant, Breathable Microfiber– Includes Fitted, Flat Sheet & Pillowcase Sets (Black)',
    productSku: 'B0FCZT13SN',
    productTitle: 'SKU BEDDORA-MFSS-4PC-KING-CAVIAR\nBeddora King Sheets Set – 4 Piece Soft & Cooling King Bed ... ts (Black)',
    productImage: 'https://via.placeholder.com/50x50?text=Sheets',
    comment: '',
    marketplace: 'Amazon.com',
    marketplaceCode: 'US',
    priority: 'major',
    resolved: false,
    type: 'title_change',
  },
]
