import { EbayProduct } from '@/services/api/ebayProducts.api'

export const mockEbayProducts: EbayProduct[] = [
  {
    id: '1',
    sku: 'BDMFTHROWPILLOW2PK18X18WHITE_2_Wh',
    title: '18x18 Throw Pillow Inserts Set Square Decorative Cushions Sofa Couch Bed (Color: White, Sets: 2)',
    price: 18.74,
    image: 'https://via.placeholder.com/60x60?text=Pillow',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '2',
    sku: 'BDMFTHROWPILLOW4PK18X18WHITE_4_Wh',
    title: '18x18 Throw Pillow Inserts Set Square Decorative Cushions Sofa Couch Bed (Color: White, Sets: 4)',
    price: 24.99,
    image: 'https://via.placeholder.com/60x60?text=Pillow',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '3',
    sku: 'Beddora-MF-4PC SHEET SET-Gray-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Gray, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '4',
    sku: 'BEDDORA-MF-4PC-DBL-NORTHERN-Light Gray - Full',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Light Gray, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '5',
    sku: 'Beddora-MF-4PC SHEET SET-White-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: White, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '6',
    sku: 'Beddora-MF-4PC SHEET SET-Orange Rust-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Orange Rust, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '7',
    sku: 'Beddora-MF-4PC SHEET SET-Black-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Black, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '8',
    sku: 'Beddora-MF-4PC SHEET SET-Beige-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Beige, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '9',
    sku: 'Beddora-MF-4PC SHEET SET-Navy-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Navy, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
  {
    id: '10',
    sku: 'Beddora-MF-4PC SHEET SET-LT Pink-FULL',
    title: '4 Piece Bed Sheet Set Hotel Luxury Microfiber Cooling Deep Pocket Wrinkle Free (Color: Light Pink, Size: Full)',
    price: 21.24,
    image: 'https://via.placeholder.com/60x60?text=Sheet',
    tags: [],
    amazonProductLink: 'Link to an amazon product',
    listingStatus: 'listed',
    cogs: 0.00,
    fbmShippingCost: 'auto',
  },
]
