import { InventorySummary, ProductInventoryItem } from '@/services/api/inventoryPlanner.api'

/**
 * Mock Inventory Summary Data
 */
export const mockInventorySummary: InventorySummary[] = [
  {
    location: 'fba',
    units: 6387,
    costOfGoods: 16853.41,
    potentialSales: 181407.54,
    potentialProfit: 237536.89,
  },
  {
    location: 'prep',
    units: 9410,
    costOfGoods: 11119.20,
    potentialSales: 0,
    potentialProfit: 0,
  },
  {
    location: 'ordered',
    units: 0,
    costOfGoods: 0,
    potentialSales: 0,
    potentialProfit: 0,
  },
]

/**
 * Mock Product Inventory Data
 */
export const mockProductInventory: ProductInventoryItem[] = [
  {
    id: '1',
    sku: 'B0F4RTTQXQ',
    asin: 'B0F4RTTQXQ',
    title: 'Beddora Black Velvet Hangers 50 Pack,Heavy Duty Coat Hanger for...esses,Suit',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 960,
    reserved: 291,
    salesVelocity: 40.10,
    daysOfStockLeft: 0,
    sentToFba: 59,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: -12,
    recommendedQuantity: 3649,
    stockValue: 16936.44,
    roi: 52,
    comment: '',
    supplier: 'Supplier A',
    leadTime: 30,
    tags: ['FBA'],
  },
  {
    id: '2',
    sku: 'B0FNBXLBWJ',
    asin: 'B0FNBXLBWJ',
    title: 'Beddora 2 Pack Pillow Protectors King Size – Waterproof Zippered Pillo...r Sleeping',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 105,
    reserved: 2,
    salesVelocity: 4.18,
    daysOfStockLeft: 26,
    sentToFba: 0,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: -19,
    recommendedQuantity: 380,
    stockValue: 0.00,
    roi: 0,
    comment: '',
    supplier: 'Supplier B',
    leadTime: 45,
    tags: ['FBA'],
  },
  {
    id: '3',
    sku: 'B0FF79YFWY',
    asin: 'B0FF79YFWY',
    title: 'Beddora Bed Pillows for Sleeping Queen Size (Grey), Set of 2, Gusseted...h Sleepers',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 14,
    reserved: 7,
    salesVelocity: 3.55,
    daysOfStockLeft: 6,
    sentToFba: 0,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: -39,
    recommendedQuantity: 323,
    stockValue: 179.00,
    roi: -104,
    comment: '',
    supplier: 'Supplier A',
    leadTime: 30,
    tags: ['FBA'],
  },
  {
    id: '4',
    sku: 'B0FCZV4BDT',
    asin: 'B0FCZV4BDT',
    title: 'Beddora Queen Sheets Set – 4 Piece Soft & Cooling Queen Bed Sheets S...ets (Gray)',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 780,
    reserved: 162,
    salesVelocity: 2.98,
    daysOfStockLeft: 316,
    sentToFba: 6,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 273,
    recommendedQuantity: 0,
    stockValue: 0.00,
    roi: 0,
    comment: '',
    supplier: 'Supplier C',
    leadTime: 60,
    tags: ['FBA', 'COGS'],
  },
  {
    id: '5',
    sku: 'B0FSN48L9M',
    asin: 'B0FSN48L9M',
    title: 'Beddora 18x18 Pillow Inserts, Set of 2, White, Indoor Decorative Thr...on Inserts',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 8,
    reserved: 2,
    salesVelocity: 1.77,
    daysOfStockLeft: 0,
    sentToFba: 570,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 0,
    recommendedQuantity: 128,
    stockValue: 1925.60,
    roi: -173,
    comment: '',
    supplier: 'Supplier B',
    leadTime: 45,
    tags: ['FBA'],
  },
  {
    id: '6',
    sku: 'B0FLG3SXRC',
    asin: 'B0FLG3SXRC',
    title: 'Beddora Bed Pillows for Sleeping King Size (White), Set of 2, Gussete...h Sleepers',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 86,
    reserved: 4,
    salesVelocity: 1.67,
    daysOfStockLeft: 54,
    sentToFba: 0,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 9,
    recommendedQuantity: 0,
    stockValue: 796.55,
    roi: -70,
    comment: '',
    supplier: 'Supplier A',
    leadTime: 30,
    tags: ['FBA', 'COGS'],
  },
  {
    id: '7',
    sku: 'B0FSRA29D6',
    asin: 'B0FSRA29D6',
    title: 'Beddora Fleece Blanket Throw Size Grey Color Luxury Anti-Static Fuzzy ...nch, Grey)',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 168,
    reserved: 35,
    salesVelocity: 1.59,
    daysOfStockLeft: 128,
    sentToFba: 19,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 94,
    recommendedQuantity: 0,
    stockValue: 954.72,
    roi: -330,
    comment: '',
    supplier: 'Supplier C',
    leadTime: 60,
    tags: ['FBA', 'COGS'],
  },
  {
    id: '8',
    sku: 'B0FSPA429X',
    asin: 'B0FSPA429X',
    title: 'Beddora Velvet Hangers 30 Pack, Space Saving Non Slip Hangers, Ultra T...ain, Grey)',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 342,
    reserved: 78,
    salesVelocity: 1.45,
    daysOfStockLeft: 253,
    sentToFba: 0,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 219,
    recommendedQuantity: 0,
    stockValue: 1823.40,
    roi: -89,
    comment: '',
    supplier: 'Supplier B',
    leadTime: 45,
    tags: ['FBA'],
  },
  {
    id: '9',
    sku: 'B0FN48L7KM',
    asin: 'B0FN48L7KM',
    title: 'Beddora Queen Size Bed Sheets Set – 4 Piece Cooling Sheets, Hotel Lux...hite, Grey)',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 245,
    reserved: 52,
    salesVelocity: 1.38,
    daysOfStockLeft: 194,
    sentToFba: 12,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 160,
    recommendedQuantity: 0,
    stockValue: 2156.80,
    roi: 28,
    comment: '',
    supplier: 'Supplier A',
    leadTime: 30,
    tags: ['FBA', 'COGS'],
  },
  {
    id: '10',
    sku: 'B0FRTQ8XYZ',
    asin: 'B0FRTQ8XYZ',
    title: 'Beddora Memory Foam Pillows for Sleeping, Set of 2, Adjustable Loft, ...n, Queen)',
    imageUrl: 'https://via.placeholder.com/50',
    fbaFbmStock: 92,
    reserved: 18,
    salesVelocity: 1.22,
    daysOfStockLeft: 77,
    sentToFba: 0,
    prepCenterStock: 0,
    ordered: 0,
    daysUntilNextOrder: 43,
    recommendedQuantity: 150,
    stockValue: 1245.60,
    roi: 45,
    comment: '',
    supplier: 'Supplier C',
    leadTime: 60,
    tags: ['FBA'],
  },
]
